name: grouper-web

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run compile script
      run: npm run compile
      
    - name: Create config
      run: node dist/generated/config/build.js
      
    ##- name: Publish
    ##  env:
     ##   CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
     ## run: |
     ##   npm install @cloudflare/wrangler -g
     ##   wrangler publish --env production
        
    ##- name: Run
     ## run: node dist/generated/config/build.js