compatibility_date = "2024-04-09"
main = "./dist/worker/index.js"
name = "grouper-web"
keep_vars = true

d1_databases = [
    { database_name = "form submissions", binding = "form_submission_store", database_id = "<DATABASE_ID>" },
    { database_name = "form info", binding = "form_info_store", database_id = "<DATABASE_ID>" },
    { database_name = "events", binding = "events_store", database_id = "<DATABASE_ID>" },
]

[build]
command = "npx typia generate --input src && tsc --project wrangler.tsconfig.json"